<?php

namespace backend\models\product;

use Yii;

/**
 * This is the model class for table "products_props".
 *
 * @property int $prop_id
 * @property int $product_id
 * @property int $prop_type_id

 *
 * @property Product $product
 * @property Prop $prop
 */
class ProductProp extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'products_props';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['prop_id', 'product_id'], 'required'],
            [['prop_id', 'product_id'], 'integer'],
            [['product_id'], 'exist', 'skipOnError' => true, 'targetClass' => Product::className(), 'targetAttribute' => ['product_id' => 'id']],
            [['prop_id'], 'exist', 'skipOnError' => true, 'targetClass' => Prop::className(), 'targetAttribute' => ['prop_id' => 'id']],
        ];
    }

    public function beforeSave($insert)
    {
        $this->prop_type_id = $this->prop->prop_type_id;
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'prop_id' => 'Prop ID',
            'product_id' => 'Product ID',
        ];
    }

    /**
     * Gets query for [[Product]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getProduct()
    {
        return $this->hasOne(Product::className(), ['id' => 'product_id']);
    }

    /**
     * Gets query for [[Prop]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getProp()
    {
        return $this->hasOne(Prop::className(), ['id' => 'prop_id']);
    }
}
